# Generated by Django 5.2.6 on 2026-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_foodbatch_foodconsumptionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbatch',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Número de factura', max_length=100),
        ),
        migrations.AddField(
            model_name='foodbatch',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de compra', max_digits=12),
        ),
    ]
