# Generated by Django 5.2.6 on 2026-07-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0006_add_weight_alert_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='estimated_exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='selection',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FlockShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Fecha de despacho')),
                ('invoice_number', models.CharField(help_text='Número de planilla/factura', max_length=50)),
                ('males_count', models.PositiveIntegerField(blank=True, help_text='Cantidad de machos despachados', null=True)),
                ('females_count', models.PositiveIntegerField(blank=True, help_text='Cantidad de hembras despachadas', null=True)),
                ('total_birds', models.PositiveIntegerField(help_text='Total aves despachadas')),
                ('average_weight_farm', models.DecimalField(decimal_places=2, help_text='Peso promedio en granja (kg)', max_digits=6)),
                ('total_weight_farm', models.DecimalField(decimal_places=2, help_text='Kilos totales en granja', max_digits=10)),
                ('dead_in_transit', models.PositiveIntegerField(default=0, help_text='Aves ahogadas en tránsito')),
                ('birds_received_plant', models.PositiveIntegerField(help_text='Pollos recibidos en planta')),
                ('average_weight_plant', models.DecimalField(decimal_places=2, help_text='Peso promedio en planta (kg)', max_digits=6)),
                ('total_weight_plant', models.DecimalField(decimal_places=2, help_text='Kilos recibidos en planta', max_digits=10)),
                ('plant_shrinkage_grams', models.DecimalField(decimal_places=2, help_text='Merma de planta en gramos por pollo', max_digits=6)),
                ('birds_sold', models.PositiveIntegerField(help_text='Pollos vendidos')),
                ('discount_kilos', models.DecimalField(decimal_places=2, default=0.0, help_text='Kilos descontados', max_digits=8)),
                ('total_weight_sold', models.DecimalField(decimal_places=2, help_text='Kilos netos de venta', max_digits=10)),
                ('average_weight_sold', models.DecimalField(decimal_places=2, help_text='Peso promedio de venta (kg)', max_digits=6)),
                ('total_shrinkage_grams', models.DecimalField(decimal_places=2, help_text='Merma total en gramos', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Observaciones de liquidación')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='flocks.flock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
